// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvnjsogiuxxgtfayzihf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2bmpzb2dpdXh4Z3RmYXl6aWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjUyNzYsImV4cCI6MjA2OTQwMTI3Nn0.t9aHH6fSdq67yyUdUJnZvbgLRxnhBMVpPww4nJtmpJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});